ChilliSoftMeetingManagement/Models/MeetingItemModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ChilliSoftMeetingManagement.Models
{
    public class MeetingItemModel
    {
        public Guid MeetingItemId { get; set; }
        public string MeetingItemName { get; set; }
        public Guid MeetingItemStatusId { get; set; }
        public string PersonAssigned { get; set; }
        public string Comment { get; set; }

        public virtual MeetingItemStatusModel MeetingItemStatusModel { get; set; }
        public virtual ICollection<MeetingTypeItemModel> MeetingTypeItems { get; set; }
    }
}

ChilliSoftMeetingManagement/Models/MeetingItemStatusModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ChilliSoftMeetingManagement.Models
{
    public class MeetingItemStatusModel
    {
        public Guid MeetingItemStatusId { get; set; }
        public string MeetingItemStatusName { get; set; }
        public virtual ICollection<MeetingItemModel> MeetingItems { get; set; }
    }
}

ChilliSoftMeetingManagement/Models/MeetingModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ChilliSoftMeetingManagement.Models
{
    public class MeetingModel
    {
        public System.Guid MeetingId { get; set; }
        public System.Guid MeetingTypeId { get; set; }
        public System.DateTime MeetingDate { get; set; }
        public string MeetingName { get; set; }
        public virtual MeetingTypeModel MeetingType { get; set; }
        public virtual ICollection<MeetingItemModel> MeetingItems { get; set; }
    }
}

ChilliSoftMeetingManagement/Models/MeetingTypeItemModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ChilliSoftMeetingManagement.Models
{
    public class MeetingTypeItemModel
    {
        public Guid MeetingTypeId { get; set; }
        public Guid MeetingItemId { get; set; }
        public Guid MeetingId { get; set; }

        public virtual MeetingModel MeetingModel { get; set; }
        public virtual MeetingItemModel MeetingItemModel { get; set; }
        public virtual MeetingTypeModel MeetingTypeModel { get; set; }
    }
}

ChilliSoftMeetingManagement/Models/MeetingTypeModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ChilliSoftMeetingManagement.Models
{
    public class MeetingTypeModel
    {
        public Guid MeetingTypeId { get; set; }
        public string MeetingTypeName { get; set; }
        public string MeetingTypeCode { get; set; }
        public virtual ICollection<MeetingModel> Meetings { get; set; }
        public virtual ICollection<MeetingTypeItemModel> MeetingTypeItems { get; set; }
    }
}

ChilliSoftMeetingManagement/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ChilliSoftMeetingManagement.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

ChilliSoftMeetingManagement/Controllers/MeetingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ChilliSoftMeetingManagement.Service;
using ChilliSoftMeetingManagement.Models;

namespace ChilliSoftMeetingManagement.Controllers
{
    public class MeetingController : Controller
    {
        MeetingService svc = new MeetingService();

        // GET: Meeting
        public ActionResult Index()
        {
            try
            {
                Guid meetingType = Guid.Parse("cda9bd2c-dd50-4e9b-af2a-b0d44e11e2cf");
                Guid meetingId = Guid.Parse("9f17d769-ba61-4225-b1ab-e70e10cee52a");

                var result = svc.GetMeetingItems(meetingType, meetingId);

                ViewBag.Meetings = result;

                return View(result);
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }

        // GET: Meeting/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Meeting/Create
        [HttpPost]
        public ActionResult Create(MeetingModel meetingModel)
        {
            try
            {
                // TODO: Add insert logic here
                var result = svc.AddMeeting(meetingModel);

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }

        // GET: Meeting/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Meeting/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, MeetingItemModel meetingItemModel)
        {
            try
            {
                // TODO: Add update logic here
                var result = svc.UpdateMeetingItemStatus(meetingItemModel);

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }
    }
}

ChilliSoftMeetingManagement/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

ChilliSoftMeetingManagement/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ChilliSoftMeetingManagement/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

ChilliSoftMeetingManagement/Views/Meeting/Index.cshtml
@*@model IEnumerable<ChilliSoftMeetingManagement.Repository.EF.Meeting>*@

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<div class="container-fluid">

    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">All Meetings</h1>
    <p class="mb-4">
        Summary of all meetings.<br />
        <span><h6><i> To view more details on the Meeting item please click on the row you want to view.</i></h6></span>
    </p>
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Meetings Listed</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <a href="#" class="btn btn-primary" onclick="AddEditMeetingItem(0)" data-toggle="tooltip" data-placement="bottom" title="Add Meeting Item">Add</a>
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0" style="font-size:8pt">
                    <thead>
                        <tr class="btn-primary">
                            <th>Meeting Item</th>
                            <th>Comment</th>
                            <th>Status</th>
                            <th>Action By</th>
                        </tr>
                    </thead>

                    <tbody>

                        @foreach (var item in ViewBag.Meetings)
                        {
                            <tr>
                                <td>
                                        @item.MeetingItemName
                                    </td>
                                    <td>
                                        @item.Comment
                                    </td>
                                    <td>
                                        @item.MeetingItemStatusModel
                                    </td>
                                    <td>
                                        @item.PersonAssigned
                                    </td>
                                <td>
                                    <div class="btn-group btn-group-sm">
                                        <input id="HiddenId" type="hidden" @item.Id />
                                            <button class="btn btn-sm btn-primary" data-toggle="tooltip" data-placement="bottom" title="Attachments" onclick="Attachments(@item.Id)">
                                                <span class="glyphicon glyphicon-paperclip"></span>
                                            </button>
                                            <a href="#" class="btn btn-success" data-toggle="tooltip" data-placement="bottom" title="Edit" onclick="AddEditJob(@item.Id)"><i class="glyphicon glyphicon-pencil"></i> </a>
                                            <button class="btn btn-default btn-danger btn-sm" data-toggle="tooltip" data-placement="bottom" title="Delete this position" onclick="ConfirmPosition(@item.Id)">
                                                <span class="glyphicon glyphicon-trash"></span>
                                            </button>
                                    </div>
                                </td>
                            </tr>
                        }
                    </tbody>

                </table>
            </div>
        </div>
    </div>
</div>

ChilliSoftMeetingManagement/Views/Meeting/_Index.cshtml
@model IEnumerable<ChilliSoftMeetingManagement.Repository.EF.Meeting>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.MeetingDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MeetingName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MeetingType.MeetingTypeName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.MeetingDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MeetingName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MeetingType.MeetingTypeName)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.MeetingId }) |
            @Html.ActionLink("Details", "Details", new { id=item.MeetingId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.MeetingId })
        </td>
    </tr>
}

</table>

ChilliSoftMeetingManagement/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Chillisoft</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <link href="~/wwwroot/bower_components/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <!-- DataTables -->
    <link href="~/wwwroot/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css" rel="stylesheet" />
    <!-- Font Awesome -->
    <link href="~/wwwroot/bower_components/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
    <!-- Ionicons -->
    <link rel="stylesheet" href="~/wwwroot/bower_components/Ionicons/css/ionicons.min.css">
    <!-- Theme style -->
    <link href="~/wwwroot/dist/css/AdminLTE.min.css" rel="stylesheet" />
    <link href="~/wwwroot/dist/css/skins/skin-blue.min.css" rel="stylesheet" />
    <!-- Google Font -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <script src="~/Scripts/bootstrap.min.js"></script>
    @* Add Jquery Library *@
    <script src="~/Scripts/jquery-2.2.3.min.js"></script>
    <script src="~/Scripts/jquery.signalR-2.4.2.min.js"></script>
    <script src="/signalr/hubs"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>


    @* Add css  *@
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />

    <style type="text/css">
        /*Added css for design notification area, you can design by your self*/
        /* COPY css content from youtube video description*/
        .noti-content {
            position: fixed;
            right: 100px;
            background: #e5e5e5;
            border-radius: 4px;
            top: 47px;
            width: 250px;
            display: none;
            border: 1px solid #9E988B;
        }

        ul#notiContent {
            max-height: 200px;
            overflow: auto;
            padding: 0px;
            margin: 0px;
            padding-left: 20px;
        }

            ul#notiContent li {
                margin: 3px;
                padding: 6px;
                background: #fff;
            }

        .noti-top-arrow {
            border-color: transparent;
            border-bottom-color: #F5DEB3;
            border-style: dashed dashed solid;
            border-width: 0 8.5px 8.5px;
            position: absolute;
            top: -8px;
        }

        span.noti {
            color: white;
            /*color: #FF2323;*/
            margin: 15px;
            position: fixed;
            /*right: 100px;*/
            /*right: 280px;*/
            right: 298px;
            font-size: 18px;
            cursor: pointer;
        }

        span.count {
            position: relative;
            top: -3px;
        }
    </style>
</head>

<body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">
        <!-- Main Header -->
        <header class="main-header">
            <!-- Logo -->
            <a href="index2.html" class="logo">
                <!-- mini logo for sidebar mini 50x50 pixels -->
                <span class="logo-mini"><b>Chilli</b>Soft</span>
                <!-- logo for regular state and mobile devices -->
                <span class="logo-lg"><b>Chi </b>Chillisoft</span>
            </a>
            <!-- Header Navbar -->
            <nav class="navbar navbar-static-top" role="navigation">
                <!-- Sidebar toggle button-->
                <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                    <span class="sr-only">Toggle navigation</span>
                </a>
                <!-- Navbar Right Menu -->
                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">
                        <!-- User Account Menu -->
                        <li class="dropdown user user-menu">
                            <!-- Menu Toggle Button -->
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <!-- The user image in the navbar-->
                                <img src="~/wwwroot/dist/img/Luleleko Booi.jpeg" class="user-image" alt="User Image">
                                <!-- hidden-xs hides the username on small devices so only the image appears. -->
                                <span class="hidden-xs">[@Session["UserName"]]</span>
                            </a>
                            <ul class="dropdown-menu">
                                <!-- The user image in the menu -->
                                <li class="user-header">
                                    <img src="~/wwwroot/dist/img/Luleleko Booi.jpeg" class="img-circle" alt="User Image">
                                    <p>
                                        Luleko Booi: Systems Software Developer

                                        <small>Chillisoft</small>
                                    </p>
                                </li>
                                <!-- Menu Body -->
                                <li class="user-body">
                                    <div class="row">
                                        <div class="col-xs-4 text-center">
                                            <a href="#">Account</a>
                                        </div>
                                    </div>
                                    <!-- /.row -->
                                </li>
                                <!-- Menu Footer-->
                                <li class="user-footer">
                                    <div class="pull-left">
                                        <a href="#" class="btn btn-default btn-flat">Profile</a>
                                    </div>
                                    <div class="pull-right">
                                        <a href="#" class="btn btn-default btn-flat">Sign out</a>
                                    </div>
                                </li>
                            </ul>
                        </li>

                    </ul>

                </div>
                <span class="noti glyphicon glyphicon-bell"><span class="count">&nbsp;</span></span>
                <div class="noti-content">
                    <div class="noti-top-arrow"></div>
                    @*<ul id="notiContent">*@
                    <fieldset style="border:solid;">
                        <a href="#" id="notiContent"></a>
                        <br />
                    </fieldset>
                    @*</ul>*@
                </div>
            </nav>
        </header>
        <!-- Left side column. contains the logo and sidebar -->
        <aside class="main-sidebar">
            <!-- sidebar: style can be found in sidebar.less -->
            <section class="sidebar">
                <!-- Sidebar user panel (optional) -->
                <div class="user-panel">
                    <div class="pull-left image">
                        <img src="~/wwwroot/dist/img/Luleleko Booi.jpeg" class="img-circle" alt="User Image">
                    </div>
                    <div class="pull-left info">
                        <p>Luleko Booi</p>
                        <!-- Status -->
                        <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
                    </div>
                </div>
                <!-- search form (Optional) -->
                <form action="#" method="get" class="sidebar-form">
                    <div class="input-group">
                        <input type="text" name="q" class="form-control" placeholder="Search...">
                        <span class="input-group-btn">
                            <button type="submit" name="search" id="search-btn" class="btn btn-flat">
                                <i class="fa fa-search"></i>
                            </button>
                        </span>
                    </div>
                </form>
                <!-- /.search form -->
                <!-- Sidebar Menu -->
                @Html.Partial("_MainMenu")
                <!-- /.sidebar-menu -->
            </section>
            <!-- /.sidebar -->
        </aside>
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            @RenderBody()
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
        <!-- Main Footer -->
        <footer class="main-footer">
            <!-- Default to the left -->
            <strong>Copyright &copy; 2021 <a href="#">Luleko Booi</a>.</strong> All rights reserved.
        </footer>
    </div>
    <!-- ./wrapper -->
    <!-- REQUIRED JS SCRIPTS -->
    <!-- jQuery 3 -->
    @*<script src="~/wwwroot/bower_components/jquery/dist/jquery.min.js"></script>*@
    <!-- Bootstrap 3.3.7 -->
    <script src="~/wwwroot/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/wwwroot/dist/js/adminlte.min.js"></script>

</body>
</html>

ChilliSoftMeetingManagement/Views/Shared/_MainMenu.cshtml
<ul class="sidebar-menu" data-widget="tree">
    <li class="header">HEADER</li>

    <!-- Optionally, you can add icons to the links -->
    <li class="treeview">
        <a href="#">
            <i class="fas fa-handshake"></i> <span> Meetings</span>
            <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
            </span>
        </a>
        <ul class="treeview-menu">
            <li><a href="@Url.Action("Index", "Meeting")"> Meetings</a></li>
        </ul>
    </li>
    <li class="treeview">
        <a href="#">
            <i class="fa fa-bar-chart"></i> <span>Reports</span>
            <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
            </span>
        </a>
        <ul class="treeview-menu">
            <li><a href="@Url.Action("#", "#")">MANCO</a></li>
            <li><a href="@Url.Action("#", "#")">Finance</a></li>
            <li><a href="@Url.Action("#", "#")">Project Team Leaders</a></li>
        </ul>
    </li>
</ul>